# Generated by Django 4.0.1 on 2022-02-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerCL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
                ("date_creat", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagCL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("tags", models.ManyToManyField(to="cloth.TagCL")),
            ],
            options={
                "verbose_name": "Одежда",
                "verbose_name_plural": "Одежды1",
            },
        ),
        migrations.CreateModel(
            name="OrderCL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Обробатывается", "Обробатывается"),
                            ("Выехал", "Выехал"),
                            ("Доставлен", "Доставлен"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "cloth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_product",
                        to="cloth.productcl",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cloth.customercl",
                    ),
                ),
            ],
        ),
    ]
