# Generated by Django 4.0.1 on 2022-02-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloth", "0002_alter_productcl_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customercl",
            old_name="date_creat",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="ordercl",
            old_name="cloth",
            new_name="clothes",
        ),
    ]
