# Generated by Django 4.0.1 on 2022-01-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='updated_day',
        ),
        migrations.AlterField(
            model_name='book',
            name='created_day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
