# Generated by Django 4.0.1 on 2022-01-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_updated_day_alter_book_created_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('activity', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Writer', 'Writer'), ('Mangaka', 'Mangaka'), ('Journalist', 'Journalist'), ('IT Developer', 'IT Developer')], max_length=100)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_expert', to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='book.book')),
            ],
        ),
    ]
