# Generated by Django 4.0.1 on 2022-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bookexpert_bookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookexpert',
            name='personal_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
