# Generated by Django 4.0.1 on 2022-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_bookexpert_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexpert',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
