# Generated by Django 4.0.1 on 2022-01-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_bookexpert_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookexpert',
            old_name='full_name',
            new_name='full_name_of_Author',
        ),
    ]
