# Generated by Django 4.0.1 on 2022-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_full_name_bookexpert_full_name_of_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookexpert',
            old_name='full_name_of_Author',
            new_name='full_name_of_Expert',
        ),
    ]
