# Generated by Django 4.0.1 on 2022-01-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.IntegerField(choices=[(1, 'BATKEN'), (2, 'CHUY'), (3, 'OSH'), (4, 'TALAS'), (5, 'NARYN'), (6, 'DJALAL-ABAD'), (7, 'ISSYK-KOL')], default=1, verbose_name='Область'),
            preserve_default=False,
        ),
    ]
